# Generated by Django 5.2.4 on 2025-08-25 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crm',
            old_name='action',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='crm',
            old_name='address',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crm',
            old_name='contact_person',
            new_name='project_value',
        ),
        migrations.RenameField(
            model_name='crm',
            old_name='email',
            new_name='software',
        ),
        migrations.AddField(
            model_name='crm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crm',
            name='start_date',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
