# Generated by Django 5.2.4 on 2025-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_action_crm_end_date_rename_address_crm_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crm',
            old_name='end_date',
            new_name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='crm',
            name='start_date',
        ),
    ]
