# Generated by Django 5.2.4 on 2025-08-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_end_date_crm_start_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=225, null=True)),
                ('Contact_person', models.CharField(blank=True, max_length=225, null=True)),
                ('project_amount', models.CharField(blank=True, max_length=225, null=True)),
                ('my_commission', models.CharField(blank=True, max_length=225, null=True)),
                ('my_percentage', models.CharField(blank=True, max_length=225, null=True)),
                ('total_pay', models.CharField(blank=True, max_length=225, null=True)),
                ('withdraw_payment', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
