# Generated by Django 5.2.4 on 2025-08-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_adminpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpayments',
            name='employee_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
