# Generated by Django 5.2.4 on 2025-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_all_bills', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Fieldwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('upload_photos', models.ImageField(upload_to='field_work/')),
                ('lead_status', models.CharField(max_length=100)),
                ('project_value', models.CharField(max_length=100)),
            ],
        ),
    ]
